### PR TITLE
Stable/ocata for master

### PR DESCRIPTION
**Pull request by tbachman**
This branch will be merged to master, so that master can
track the stable/ocata branch

### CODE REVIEW

**Comment by amittbose** [comment]
Can you also update the version in setup.py to 6.0.0?

**Comment by tbachman** [comment]
Good call -- will chage.

**Comment by snaiksat** [comment]
Hi Thomas, I also seemed to have added this note in my commit:
The ``dhcp_domain`` DHCP agent configuration option was deprecated in
Liberty cycle in Neutron, and now is now no longer used.
The ``dns_domain`` option should be used instead.

The idea was to highlight this change. If it's not too much work, could you add it to your commit message?

**Comment by tbachman** [comment]
Definitely -- and thanks!

**Comment by tbachman** [comment]
Pushed update to address reviewer comments.

**Pull request merged**
