### PR TITLE
request_* RPC API should be of type cast

### PR DESCRIPTION
**Pull request by ivar-lazzaro**
Set fanout to False to make sure only one server at a time serves
the call.

### CODE REVIEW

**Comment by ivar-lazzaro** [comment]
The previous change was made to prevent all the servers from being clogged by the agents' requests. However, by using call instead of cast we also made the RPC blocking, which is not how the agent was designed.
By setting fanout to False, we make sure that only one server at a time can serve the RPC in an asynchronous and round robin fashion

**Comment by tbachman** [comment]
Thanks -- but was hoping we could put that in the commit message?

**Comment by snaiksat** [comment]
So my memory is a little bit vague as to why I chose to use call instead of cast here. There are two possibilities, I either tried setting fanout=False and it didn't work, hence resorted to using call, or I simply didn't recognize the point that we were trying to get the response back asynchronously. But, assuming that setting fanout=False does work correctly, the fix in this patch is definitely seems to be the right solution in the context of what we seem to want to achieve.

**Comment by tbachman** [comment]
Again, all good -- just would love to have this captured in the commit message, since the PR comments don't show up in the git history.

**Comment by ivar-lazzaro** [comment]
Updated commit message

**Pull request merged**
